version: "3.0"
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: EntitySynonymMapper
  - name: DIETClassifier
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.3

policies:
  - name: MemoizationPolicy
  - name: RulePolicy

assistant_id: 20250711-092454-ordered-crowd

